# Generated by Django 3.2.16 on 2024-03-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoControlFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto_control', models.CharField(max_length=15, unique=True)),
                ('nombre_producto_control', models.CharField(max_length=15, unique=True)),
                ('registro_ica_producto_control', models.CharField(max_length=15, unique=True)),
                ('frecuencia_producto_control', models.IntegerField(default=0)),
                ('ultima_aplicacion_producto_control_fertilizante', models.DateField()),
            ],
            options={
                'verbose_name': 'Prodcuto Fertilizante',
                'verbose_name_plural': 'Productos Fertilizantes',
            },
        ),
        migrations.CreateModel(
            name='ProductoControlHongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto_control', models.CharField(max_length=15, unique=True)),
                ('nombre_producto_control', models.CharField(max_length=15, unique=True)),
                ('registro_ica_producto_control', models.CharField(max_length=15, unique=True)),
                ('frecuencia_producto_control', models.IntegerField(default=0)),
                ('nombre_hongo', models.CharField(max_length=15)),
                ('carencia_periodo_hongo', models.DateField()),
            ],
            options={
                'verbose_name': 'Prodcuto Hongo',
                'verbose_name_plural': 'Productos Hongos',
            },
        ),
        migrations.CreateModel(
            name='ProductoControlPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto_control', models.CharField(max_length=15, unique=True)),
                ('nombre_producto_control', models.CharField(max_length=15, unique=True)),
                ('registro_ica_producto_control', models.CharField(max_length=15, unique=True)),
                ('frecuencia_producto_control', models.IntegerField(default=0)),
                ('carencia_producto_control_plaga', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Prodcuto Plaga',
                'verbose_name_plural': 'Productos Plagas',
            },
        ),
    ]
