# Generated by Django 3.2.16 on 2024-03-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoControl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoControlFertilizante',
            new_name='Fertilizante',
        ),
        migrations.RenameField(
            model_name='fertilizante',
            old_name='ultima_aplicacion_producto_control_fertilizante',
            new_name='ultima_aplicacion_fertilizante',
        ),
    ]
