# Generated by Django 3.2.16 on 2024-03-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoControl', '0003_auto_20240319_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoControlHongo',
            new_name='Hongo',
        ),
    ]
