# Generated by Django 3.2.16 on 2024-03-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoControl', '0004_rename_productocontrolhongo_hongo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizante',
            name='valor_producto_control',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hongo',
            name='valor_producto_control',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plaga',
            name='valor_producto_control',
            field=models.IntegerField(default=0),
        ),
    ]
