# Generated by Django 3.2.16 on 2024-03-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productor', '0001_initial'),
        ('productoControl', '0005_auto_20240319_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cultivo', models.CharField(max_length=20, unique=True)),
                ('nombre_cultivo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
            },
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vivero', models.CharField(max_length=20, unique=True)),
                ('nombre_vivero', models.CharField(max_length=20, unique=True)),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vivero.cultivo')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productor.productor')),
            ],
            options={
                'verbose_name': 'Vivero',
                'verbose_name_plural': 'Viveros',
            },
        ),
        migrations.CreateModel(
            name='LaborFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_labor', models.DateTimeField()),
                ('descripcion_labor', models.TextField(max_length=250)),
                ('codigo_producto_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productoControl.fertilizante')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vivero.cultivo')),
            ],
            options={
                'verbose_name': 'Labor Fertilizante',
                'verbose_name_plural': 'Labor Fertilizantes',
            },
        ),
    ]
