# Generated by Django 3.2.16 on 2024-03-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productoControl', '0005_auto_20240319_0045'),
        ('vivero', '0002_laborhongo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_labor', models.DateTimeField()),
                ('descripcion_labor', models.TextField(max_length=250)),
                ('codigo_producto_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productoControl.plaga')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vivero.cultivo')),
            ],
            options={
                'verbose_name': 'Labor Plaga',
                'verbose_name_plural': 'Labor Plagas',
            },
        ),
    ]
